server:
  port: 8888

spring:
  datasource:
    name: encrypted_im
    url: jdbc:mysql://127.0.0.1:3306/encrypted_im
    username: root
    password: lzd1219
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml    # 对应mapper映射xml文件的所在路径
  type-aliases-package: org.linux.encrypted_im.entity   # 对应实体类的路径
debug: true